components:
  parameters:
    productIdPath:
      name: productId
      in: path
      description: Identifier of product
      required: true
      schema:
        type: string
      example: '123456789'

  schemas:
    ProductFilterOrder:
      type: string
      description: order of the product listing
      enum:
        - 'NAME'
        - 'TYPE_ID'
      x-enum-varnames:
        - NAME
        - TYPE_ID

    ProductStatus:
      type: string
      description: status of the product
      enum:
        - 'PUBLISHED'
        - 'UNPUBLISHED'
      x-enum-varnames:
        - PUBLISHED
        - UNPUBLISHED

    Product:
      type: object
      description: Product information
      required:
        - versionId
        - code
        - effectiveDate
        - typeId
        - name
        - status
      properties:
        versionId:
          type: string
          description: Identifier of product version
          example: '123456789::2025-08-01T09:00:00Z'
        code:
          type: string
          description: Code of the product
          example: '123456789'
        effectiveDate:
          type: string
          format: date-time
          description: Effective date of the product
          example: '2025-08-01T09:00:00Z'
        typeId:
          type: string
          description: Identifier of the product type
          example: 'fruit'
        name:
          type: object
          additionalProperties:
            type: string
          description: Name of the product
          example:
            es: 'Manzana'
            en: 'Apple'
        status:
          $ref: '#/components/schemas/ProductStatus'

    ProductSummary:
      type: object
      description: Product summary information
      required:
        - versionId
        - code
        - effectiveDate
        - name
        - status
      properties:
        versionId:
          type: string
          description: Identifier of the product version
          example: '123456789::2025-08-01T09:00:00Z'
        code:
          type: string
          description: Code of the product
          example: '123456789'
        effectiveDate:
          type: string
          format: date-time
          description: Effective date of the product
          example: '2025-08-01T09:00:00Z'
        typeId:
          type: string
          description: Identifier of the product type
          example: 'fruit'
        name:
          type: object
          additionalProperties:
            type: string
          description: Name of the product
          example:
            es: 'Manzana'
            en: 'Apple'
        status:
          $ref: '#/components/schemas/ProductStatus'

    ProductSummaryList:
      type: object
      required:
        - pageNumber
        - pageSize
        - totalItems
        - items
      properties:
        pageNumber:
          type: integer
          description: Number of total pages
        pageSize:
          type: integer
          description: Size of each page
        totalItems:
          type: integer
          description: Number of total items
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductSummary'

    CreateProductInput:
      type: object
      description: Create product input
      required:
        - versionId
        - typeId
        - name
      properties:
        versionId:
          type: string
          description: Identifier of the product
          example: '123456789::2025-08-01T09:00:00Z'
        typeId:
          type: string
          description: Identifier of the product type
          example: 'fruit'
        name:
          type: object
          additionalProperties:
            type: string
          description: Name of the product
          example:
            es: 'Manzana'
            en: 'Apple'

    UpdateProductInput:
      type: object
      description: Create product input
      required:
        - name
      properties:
        name:
          type: object
          additionalProperties:
            type: string
          description: Name of the product
          example:
            es: 'Manzana'
            en: 'Apple'
