metadata:
  application-id: ecommerce
  environment: local


spring:
  application:
    name: ${metadata.application-id}

  profiles:
    active: ${metadata.environment}
    include:
      - shared


logging:
  level:
    root: WARN
    com.jeferro: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

shared:
  auth:
    rest:
      issuer: ${metadata.application-id}


application:
  product-versions:
    topic: com.jeferro.${metadata.application-id}.${metadata.environment}.product-versions.v1

  reviews:
    product-versions-consumer-group-id: ${metadata.application-id}.${metadata.environment}.product_versions.reviews
