
name: 'PR checker'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
#    paths:
#      - code/**
#      - apis/**

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Install ASDF
        uses: ./.github/actions/asdf-install

      - name: Check Java version
        run: java -version

      - name: Build
        run: task build
        env:
          # disable default JVM in container
          JAVA_HOME: ""

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Install ASDF
        uses: ./.github/actions/asdf-install

      - name: Test
        run: task build
